export const PATIENT_REQUEST = "PATIENT_REQUEST"
export const PATIENT_SUCCESS = "PATIENT_SUCCESS"
export const PATIENT_FAILURE = "PATIENT_FAILURE"

export const PAGINATE_REQUEST = "PAGINATE_REQUEST"
export const PAGINATE_SUCCESS = "PAGINATE_SUCCESS"
export const PAGINATE_FAILURE = "PAGINATE_FAILURE"

export const SEARCH_PATIENT_REQUEST = "SEARCH_PATIENT_REQUEST"
export const SEARCH_PATIENT_SUCCESS = "SEARCH_PATIENT_SUCCESS"
export const SEARCH_PATIENT_FAILURE = "SEARCH_PATIENT_FAILURE"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const DELETE_REQUEST = "DELETE_REQUEST"
export const DELETE_SUCCESS = "DELETE_SUCCESS"
export const DELETE_FAILURE = "DELETE_FAILURE"


export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGOUT_ADMIN = "LOGOUT_ADMIN"

